"""Haiti Nippes GIS and recovery-analysis package."""

from haiti_nippes.access_model import (
    CommuneAccessProfile,
    DataQuality,
    FacilityType,
    HealthFacility,
    RoadSegmentStatus,
    WashAccessRecord,
)
from haiti_nippes.commune_index import (
    CommuneAccessIndexRow,
    CommuneAccessInput,
    build_commune_access_index,
    build_commune_access_row,
)
from haiti_nippes.flood_road_index import (
    ChokepointPriorityRow,
    FloodExposurePriorityRow,
    RoadDisruptionPriorityRow,
    build_chokepoint_priority_register,
    build_flood_exposure_register,
    build_road_disruption_register,
)
from haiti_nippes.flood_road_model import (
    DisruptionType,
    DrainageChokepoint,
    FloodExposureZone,
    PassabilityStatus,
    RoadDisruptionRecord,
)
from haiti_nippes.geography import (
    Arrondissement,
    Commune,
    Department,
    build_nippes_department,
    iter_communes,
    normalize_name,
)
from haiti_nippes.io import (
    read_commune_access_inputs,
    read_drainage_chokepoints,
    read_flood_exposure_zones,
    read_road_disruptions,
    write_chokepoint_priority_register,
    write_commune_access_index,
    write_flood_exposure_register,
    write_road_disruption_register,
)
from haiti_nippes.map_builder import build_all_maps, build_map_product
from haiti_nippes.map_config import MapBuildConfig, MapLayerSpec, MapProductSpec, map_products
from haiti_nippes.map_readiness import (
    MapReadinessRow,
    build_map_readiness_report,
    build_map_readiness_row,
    write_map_readiness_report,
)
from haiti_nippes.pipeline import PipelinePaths, PipelineResult, run_table_pipeline
from haiti_nippes.scoring import (
    ScoreWeights,
    distance_score,
    min_max_score,
    quality_from_missing,
    road_penalty_score,
    travel_time_score,
    weighted_index,
)

__all__ = [
    "Arrondissement",
    "ChokepointPriorityRow",
    "Commune",
    "CommuneAccessIndexRow",
    "CommuneAccessInput",
    "CommuneAccessProfile",
    "DataQuality",
    "Department",
    "DisruptionType",
    "DrainageChokepoint",
    "FacilityType",
    "FloodExposurePriorityRow",
    "FloodExposureZone",
    "HealthFacility",
    "MapBuildConfig",
    "MapLayerSpec",
    "MapProductSpec",
    "MapReadinessRow",
    "PassabilityStatus",
    "PipelinePaths",
    "PipelineResult",
    "RoadDisruptionPriorityRow",
    "RoadDisruptionRecord",
    "RoadSegmentStatus",
    "ScoreWeights",
    "WashAccessRecord",
    "build_all_maps",
    "build_chokepoint_priority_register",
    "build_commune_access_index",
    "build_commune_access_row",
    "build_flood_exposure_register",
    "build_map_product",
    "build_map_readiness_report",
    "build_map_readiness_row",
    "build_nippes_department",
    "build_road_disruption_register",
    "distance_score",
    "iter_communes",
    "map_products",
    "min_max_score",
    "normalize_name",
    "quality_from_missing",
    "read_commune_access_inputs",
    "read_drainage_chokepoints",
    "read_flood_exposure_zones",
    "read_road_disruptions",
    "road_penalty_score",
    "run_table_pipeline",
    "travel_time_score",
    "weighted_index",
    "write_chokepoint_priority_register",
    "write_commune_access_index",
    "write_flood_exposure_register",
    "write_map_readiness_report",
    "write_road_disruption_register",
]
