"""End-to-end table pipeline for Haiti Nippes GIS data."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from haiti_nippes.commune_index import build_commune_access_index
from haiti_nippes.flood_road_index import (
    build_chokepoint_priority_register,
    build_flood_exposure_register,
    build_road_disruption_register,
)
from haiti_nippes.io import (
    read_commune_access_inputs,
    read_drainage_chokepoints,
    read_flood_exposure_zones,
    read_road_disruptions,
    write_chokepoint_priority_register,
    write_commune_access_index,
    write_flood_exposure_register,
    write_road_disruption_register,
)


@dataclass(frozen=True)
class PipelinePaths:
    """Input and output paths for the first-pass GIS table pipeline."""

    commune_access_input: Path = Path("data/metadata/commune_access_input_template.csv")
    road_disruptions_input: Path = Path("data/metadata/road_disruptions_starter.csv")
    drainage_chokepoints_input: Path = Path("data/metadata/drainage_chokepoints_starter.csv")
    flood_exposure_input: Path = Path("data/metadata/flood_exposure_zones_starter.csv")
    commune_access_output: Path = Path("outputs/tables/commune_access_index.csv")
    road_disruptions_output: Path = Path("outputs/tables/road_disruption_register.csv")
    drainage_chokepoints_output: Path = Path("outputs/tables/chokepoint_priority_register.csv")
    flood_exposure_output: Path = Path("outputs/tables/flood_exposure_register.csv")


@dataclass(frozen=True)
class PipelineResult:
    """Row counts generated by a pipeline run."""

    commune_access_rows: int
    road_disruption_rows: int
    drainage_chokepoint_rows: int
    flood_exposure_rows: int

    def summary_lines(self) -> tuple[str, ...]:
        """Return human-readable pipeline summary lines."""
        return (
            f"commune access rows: {self.commune_access_rows}",
            f"road disruption rows: {self.road_disruption_rows}",
            f"drainage chokepoint rows: {self.drainage_chokepoint_rows}",
            f"flood exposure rows: {self.flood_exposure_rows}",
        )


def run_table_pipeline(paths: PipelinePaths | None = None) -> PipelineResult:
    """Run the first-pass GIS table pipeline."""
    target_paths = paths or PipelinePaths()

    commune_records = read_commune_access_inputs(target_paths.commune_access_input)
    road_records = read_road_disruptions(target_paths.road_disruptions_input)
    chokepoint_records = read_drainage_chokepoints(target_paths.drainage_chokepoints_input)
    flood_records = read_flood_exposure_zones(target_paths.flood_exposure_input)

    commune_rows = build_commune_access_index(commune_records)
    road_rows = build_road_disruption_register(road_records)
    chokepoint_rows = build_chokepoint_priority_register(chokepoint_records)
    flood_rows = build_flood_exposure_register(flood_records)

    write_commune_access_index(commune_rows, target_paths.commune_access_output)
    write_road_disruption_register(road_rows, target_paths.road_disruptions_output)
    write_chokepoint_priority_register(chokepoint_rows, target_paths.drainage_chokepoints_output)
    write_flood_exposure_register(flood_rows, target_paths.flood_exposure_output)

    return PipelineResult(
        commune_access_rows=len(commune_rows),
        road_disruption_rows=len(road_rows),
        drainage_chokepoint_rows=len(chokepoint_rows),
        flood_exposure_rows=len(flood_rows),
    )
